title: Dilara Isik
description: Hi! I am majoring in Computer Science at Vanderbilt University. I am very excited to bring my strong programming and collaboration skills, interdisciplinary interests and experiences, and–most importantly–passion for solving real-world problems using technology.
show_downloads: false
google_analytics:
url: "https://dilaraisik.com"
theme: jekyll-theme-cayman

